In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,50,(4,6))
arr

array([[17, 46, 39, 24, 49, 22],
       [ 1, 41, 33, 34, 26,  2],
       [39,  1, 20, 29, 25,  2],
       [45,  1, 27, 32,  2,  3]])

In [6]:
#Mean
print('Mean: ',arr.mean(axis=1))
#standard deviation
print('Standard Deviation: ',arr.std(axis=1))
#variance
print('Variance: ',arr.var(axis=1))

array([32.83333333, 22.83333333, 19.33333333, 18.33333333])

In [8]:
#b
B=[56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
arr1 = np.array(B)
print("Sorted array: ",np.sort(arr1))
print("Indices of the sorted elements of a given array: ",np.argsort(arr1))

Sorted array:  [ 8 22 24 33 41 46 48 56 78 91]
Indices of the sorted elements of a given array:  [8 2 6 9 3 7 1 0 4 5]


In [10]:
#c
m = 3
n = 4
arr2 = np.random.randint(1,100,(m,n))
print(arr2)
print('Shape: ',arr2.shape)
print('Type: ',type(arr2))
print('Data Type: ',arr2.dtype)
arr2 = arr2.reshape(n,m)
print('After reshaping: \n',arr2)
print('New Shape: ',arr2.shape)

[[ 5 63 99 76]
 [78 75 32 81]
 [62 86 55  9]]
Shape:  (3, 4)
Type:  <class 'numpy.ndarray'>
Data Type:  int32
After reshaping: 
 [[ 5 63 99]
 [76 78 75]
 [32 81 62]
 [86 55  9]]
New Shape:  (4, 3)


In [11]:
#d
x = np.array([1, 0, 3, 4, 0, 0, 3, 2, 1, np.nan, 3, np.nan])
print("ARRAY: ",x)

ARRAY:  [ 1.  0.  3.  4.  0.  0.  3.  2.  1. nan  3. nan]


In [12]:
print("Elements of the array are zero : ", np.all(x))
res = np.where(x == 0)[0]
print("Indices of zero elements: ",res)

Elements of the array are zero :  False
Indices of zero elements:  [1 4 5]


In [13]:
print("Elements of array are NaN :: ",np.isnan(x))
res = np.where(np.isnan(x) == True)[0]
print("Indices of NaN elements: ",res)

Elements of array are NaN ::  [False False False False False False False False False  True False  True]
Indices of NaN elements:  [ 9 11]
